# Generated by Django 6.0.6 on 2026-07-05 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsuarioKeepFresh",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=80)),
                ("apellido", models.CharField(max_length=80)),
                ("usuario", models.CharField(max_length=80, unique=True)),
                ("password", models.CharField(max_length=120)),
                ("cedula", models.CharField(max_length=40, unique=True)),
                (
                    "biografia",
                    models.TextField(blank=True, default="¡Pensemos en la naturaleza!"),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistorialAlimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_alimento", models.CharField(max_length=120)),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("dias_restantes", models.IntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("fresh", "Fresco"),
                            ("warning", "Maduro / Riesgo"),
                            ("expired", "Vencido"),
                        ],
                        default="fresh",
                        max_length=20,
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial",
                        to="webapp.usuariokeepfresh",
                    ),
                ),
            ],
        ),
    ]
